name: Update nixpkgs

on:
  schedule:
    - cron:  '0 1 * * 0'
  workflow_dispatch:

jobs:
  nixpkgs-update:
    name: Update nixpkgs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        version: [nixpkgs-25-11, nixpkgs-unstable]

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Run flake update
        run: >
          nix flake update ${{ matrix.version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          add-paths: |
            flake.lock
          title: "flake: flake update ${{ matrix.version }}"
          body: |
            Update shared nixpkgs version.

            After this PR is merged, run `nix flake update nixpkgs-version`
            in depending repositories.
          branch: flake-update-action-pr
          delete-branch: true
          commit-message: "flake: flake update ${{ matrix.version }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          token: ${{ secrets.PAT }}

